[package]
name = "lrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
zstd = "0.12.4"
