name: Test Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test coverage

    steps:
    - uses: actions/checkout@v3
    - name: Install llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Generate coverage
      run: cargo llvm-cov --json --output-path codecov.json
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./codecov.json
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
